name: neuronify
version: 1.0
summary: Neuronify
description: |
    Education neural network app
confinement: strict

apps:
    neuronify:
        command: neuronify
        plugs:
          - unity7
          - x11
          - opengl
          - pulseaudio

parts:
    qml:
        plugin: qt57

    move:
        plugin: copy
        files:
            neuronify: neuronify
            lib: lib
            qml: qml
            plugins: plugins

    dep:
        plugin: nil
        stage-packages:
            - libc-bin
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - shared-mime-info
            - libgdk-pixbuf2.0-0
            - libx11-xcb1
            - libgl1-mesa-dev
            - libegl1-mesa
            - libxrender-dev
            - libgpg-error0
            - libgcrypt20
            - liblzma5
            - libselinux1
            - libpcre3
            - zlib1g
            - libexpat1
            - libc6
            - libgcc1
            - libgcc-5-dev
            - libstdc++6
            - libxi6
            - libuuid1
            - libpulse-dev
            - libicu-dev
