[package]
name = "neuronify-game"
version = "0.1.0"
edition = "2021"

[lib]
name = "neuronify_game_lib"
path = "src/lib.rs"

[[bin]]
name = "neuronify-game"
path = "src/main.rs"

[[bin]]
name = "map-editor"
path = "src/bin/map_editor/main.rs"

[[bin]]
name = "gen-voronoi-map"
path = "src/bin/gen_voronoi_map.rs"

[dependencies]
neuronify-core = { path = "../neuronify-core" }
visula = { path = "/home/svenni/projects/visula/dragly-2026-04-11-fix-shadows/visula" }
visula_derive = { path = "/home/svenni/projects/visula/dragly-2026-04-11-fix-shadows/visula_derive" }
visula_core = { path = "/home/svenni/projects/visula/dragly-2026-04-11-fix-shadows/visula_core" }
wgpu = { version = "29", features = ["webgl"] }
glam = { version = "0.30", features = ["bytemuck", "serde"] }
bytemuck = { version = "1.24", features = ["derive"] }
egui = "0.34"
hecs = { version = "0.10.5", features = ["column-serialize", "serde", "row-serialize"] }
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.204"
chrono = { version = "0.4.38", features = ["serde"] }
log = "0.4"
roxmltree = "0.20"
serde_json = "1.0"

[dev-dependencies]
pollster = "0.4"
