[package]
name = "neuronify-game"
version = "0.1.0"
edition = "2021"

[dependencies]
neuronify-core = { path = "../neuronify-core" }
visula = { git = "https://github.com/dragly/visula", rev = "62dcd36c65816bb5055806f9de466499b3e6d5cd" }
visula_derive = { git = "https://github.com/dragly/visula", rev = "62dcd36c65816bb5055806f9de466499b3e6d5cd" }
visula_core = { git = "https://github.com/dragly/visula", rev = "62dcd36c65816bb5055806f9de466499b3e6d5cd" }
wgpu = { version = "27", features = ["webgl"] }
glam = { version = "0.30", features = ["bytemuck", "serde"] }
bytemuck = { version = "1.24", features = ["derive"] }
egui = "0.33"
hecs = { version = "0.10.5", features = ["column-serialize", "serde", "row-serialize"] }
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.204"
chrono = { version = "0.4.38", features = ["serde"] }
log = "0.4"
